version: "3.3"
services:
    rabbitmq01:
        build:
            context: .
            dockerfile: rabbitmq-build
        image: rabbitmq:3.8.3-custom
        ports:
            - "15671:15671"
        networks:
            - tutlab
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        env_file:
            - ./rabbitmq_env

networks:
    tutlab:

volumes:
    rabbitmq-data:
